<?php
/**
 * PO Exporter — exports string translations as PO file.
 *
 * Uses WordPress core POMO library. PO is the standard gettext format,
 * compatible with Poedit and other translation tools.
 *
 * @package SPL\Modules\PLL\ImportExport
 */

declare(strict_types=1);

namespace SPL\Modules\PLL\ImportExport\Format;

use SPL\Modules\PLL\ImportExport\ExporterInterface;
use SPL\Modules\PLL\ImportExport\FileFormatFactory;

defined( 'ABSPATH' ) || exit;

final class PoExporter implements ExporterInterface {

	private string $sourceLang;
	private string $targetLang;
	private \PO $po;

	public function __construct( string $sourceLang, string $targetLang ) {
		$this->sourceLang = $sourceLang;
		$this->targetLang = $targetLang;

		require_once ABSPATH . '/wp-includes/pomo/po.php';
		$this->po = new \PO();
	}

	public function addTranslationEntry( array $ref, string $source, string $target = '' ): void {
		if ( '' === $source ) {
			return;
		}

		$entry = new \Translation_Entry(
			[
				'singular'           => $source,
				'translations'       => [ $target ],
				'context'            => $ref['field_id'] ?? '',
				'extracted_comments' => $ref['field_comment'] ?? '',
			]
		);

		$this->po->add_entry( $entry );
	}

	public function getContent(): string {
		$this->po->set_comment_before_headers(
			'This file was generated by HD Polylang Module' . PHP_EOL
			. get_site_url() . PHP_EOL
		);

		$this->setHeaders();

		return $this->po->export();
	}

	public function getFilename(): string {
		return sprintf(
			'pll_strings_%s_%s_%s.po',
			$this->sourceLang,
			$this->targetLang,
			gmdate( 'Y-m-d' )
		);
	}

	private function setHeaders(): void {
		$this->po->set_header( 'Language', $this->targetLang );
		$this->po->set_header( 'Project-Id-Version', FileFormatFactory::APP_NAME . '/' . POLYLANG_VERSION );
		$this->po->set_header( 'POT-Creation-Date', current_time( 'Y-m-d H:iO', true ) );
		$this->po->set_header( 'PO-Revision-Date', current_time( 'Y-m-d H:iO', true ) );
		$this->po->set_header( 'MIME-Version', '1.0' );
		$this->po->set_header( 'Content-Type', 'text/plain; charset=utf-8' );
		$this->po->set_header( 'Content-Transfer-Encoding', '8bit' );
		$this->po->set_header( 'X-Source-Language', $this->sourceLang );
		$this->po->set_header( 'X-Polylang-Site-Reference', get_site_url() );
	}
}
